### ISSUE TITLE
Losing server progress on game update

### ISSUE THREAD

**Issue by ghost** [yeet-zone/docker-dontstarvetogether#136]
Whenever the game updates, my server loses player progress. All of the structures in the world remain, but when players rejoin, they are sent back to character select screen, losing their map completion and held items. 

I have been trying to fix the issue by twiddling with the start settings, but am having little luck. I have also found that my servers fail to register in the public lobby unless  --update=all or  --update=game is set. 

While it shouldn't affect anything, I will also note that I have the container set to automatically restart when it gets a bad health check. In theory, this should always keep my server up to date.

Attached is a zip file containing my `*.env`s and my `docker-compose.yml`.
My docker-compose is also provided below for convenience. 

[Homeworld.zip](https://github.com/fairplay-zone/docker-dontstarvetogether/files/3100951/Homeworld.zip)

```yaml
networks:
  dst-net:
    external:
      name: dst-net
services:
  Homeworld-cave:
    command: dst-server start --update=all --keep-configuration=token,cluster,server,world,mods
    container_name: Homeworld-cave
    env_file: Homeworld-cave.env
    hostname: Homeworld-cave
    image: dstacademy/dontstarvetogether:0.8
    networks:
    - dst-net
    ports:
    - 11002:11000/udp
    restart: unless-stopped
    stdin_open: 'true'
    tty: 'true'
    volumes:
    - ./Homeworld-cave:/var/lib/dsta/cluster
  Homeworld-forest:
    command: dst-server start --update=all --keep-configuration=token,cluster,server,world,mods
    container_name: Homeworld-forest
    env_file: Homeworld-forest.env
    hostname: Homeworld-forest
    image: dstacademy/dontstarvetogether:0.8
    networks:
    - dst-net
    ports:
    - 11001:10999/udp
    restart: unless-stopped
    stdin_open: 'true'
    tty: 'true'
    volumes:
    - ./Homeworld-forest:/var/lib/dsta/cluster
version: '2'


```
