### ISSUE TITLE
Multiple world with different overrides?

### ISSUE THREAD

**Issue by meteorlxy** [yeet-zone/docker-dontstarvetogether#83]
According to the example [Multiple Servers](https://github.com/dst-academy/docker-dontstarvetogether/blob/develop/docs/examples/multiple) or [Sharded Server](https://github.com/dst-academy/docker-dontstarvetogether/blob/develop/docs/examples/shard), if I have different `worldgenoverride.lua` (or `modoverrides.lua`) for different world, I have to start the container one by one:
```bash
export WORLD_OVERRIDES=$(< worldgenoverride_master.lua)
docker-compose up -d dst_master
export WORLD_OVERRIDES=$(< worldgenoverride_cave.lua)
docker-compose up -d dst_cave
```
Is there a better solution?

**Comment by thasmo** [comment]
@meteorlxy You can try [variable substitution](https://docs.docker.com/compose/compose-file/#variable-substitution) in the `docker-compose.yml` file directly. Something like this could work:

`shell`:
```sh
export WORLD_OVERRIDES_MASTER=$(< worldgenoverride_master.lua)
export WORLD_OVERRIDES_CAVE=$(< worldgenoverride_cave.lua)
```

`docker-compose.yml`:
```yml
services:
  master:
    environment:
      - WORLD_OVERRIDES: ${WORLD_OVERRIDES_MASTER}
  cave:
    environment:
      - WORLD_OVERRIDES: ${WORLD_OVERRIDES_CAVE}
```

Untested. Please report back if this helps to achieve what you need. :)
